services:
  mymambo-odoo19e:
    image: odoo:19.0
    container_name: Odoo_mymambo_19
    user: root
#    user: "101:101"
#    command:
#      odoo -u all -d sales19e
    restart: always
    tty: true
    environment:
      - HOST=odoo-db
      - USER=odoo
      - PASSWORD=odoo
      - HOME=/var/lib/odoo                 # <<< wichtig
      - PYTHONUSERBASE=/var/lib/odoo/.local
      - PIP_CACHE_DIR=/var/lib/odoo/.cache/pip
      # optional, falls Logs nerven:
      - PIP_NO_CACHE_DIR=off
      - PIP_ROOT_USER_ACTION=ignore
    ports:
      - "13069:8069"
      - "13072:8072"
    volumes:
      - mymambo19-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./entrypoint.sh:/entrypoint.sh
      - ./addons:/mnt/extra-addons
    #  - ./enterprise:/mnt/enterprise:ro
      - ./backup:/var/lib/odoo/backups
    networks:
      - web
    labels:
      - "traefik.enable=true"

      # ======================================================
      # Odoo 19 – NORMALER HTTP/HTTPS TRAFFIC → Port 8069
      # mybeat-mymambo.de
      # ======================================================

      - "traefik.http.routers.mymambo19.rule=Host(`mybeat-mymambo.de`)"
      - "traefik.http.routers.mymambo19.entrypoints=websecure"
      - "traefik.http.routers.mymambo19.tls=true"
      - "traefik.http.routers.mymambo19.tls.certresolver=cloudflare"
      - "traefik.http.routers.mymambo19.middlewares=gzip-compression@file"
      - "traefik.http.routers.mymambo19.service=mymambo19"

      - "traefik.http.services.mymambo19.loadbalancer.server.port=8069"

      # ======================================================
      # Odoo 19 – WEBSOCKET /websocket → EVENT-PORT 8072
      # Höhere Priority, damit IMMER dieser Router gewinnt
      # ======================================================

      - "traefik.http.routers.mymambo19-ws.rule=Host(`mybeat-mymambo.de`) && Path(`/websocket`)"
      - "traefik.http.routers.mymambo19-ws.entrypoints=websecure"
      - "traefik.http.routers.mymambo19-ws.tls=true"
      - "traefik.http.routers.mymambo19-ws.tls.certresolver=cloudflare"
      - "traefik.http.routers.mymambo19-ws.service=mymambo19-ws"
      - "traefik.http.routers.mymambo19-ws.priority=100"

      - "traefik.http.services.mymambo19-ws.loadbalancer.server.port=8072"

networks:
  web:
    external: true
    name: traefik_default

volumes:
  mymambo19-data:
    name: mymambo_mymambo19-data
