[options]
addons_path = 
#	/mnt/enterprise,
#	/mnt/extra-addons/account-invoicing,
#	/mnt/extra-addons/account-financial-reporting,
#	/mnt/extra-addons/account-reconcile,
#	/mnt/extra-addons/bank-payment,
#	/mnt/extra-addons/bank-statement-import,
	/mnt/extra-addons/e-commerce,
#        /mnt/extra-addons/l10n-germany,
#	/mnt/extra-addons/hr,
#       /mnt/extra-addons/hr-holidays,
#	/mnt/extra-addons/knowledge,
#	/mnt/extra-addons/design-themes,
	/mnt/extra-addons/nolte-addons,
#	/mnt/extra-addons/other,
#	/mnt/extra-addons/odoo-addons-18.0,
	/mnt/extra-addons/odoo-addons,
#        /mnt/extra-addons/partner-contact,
#	/mnt/extra-addons/product-attribute,
#	/mnt/extra-addons/server-tools,
#	/mnt/extra-addons/server-ux,
#	/mnt/extra-addons/reporting-engine,
	/mnt/extra-addons/web
#	/mnt/extra-addons/website;
#	/usr/lib/python3/dist-packages/odoo/addons

admin_passwd = myodoo2018
csv_internal_sep = ,
data_dir = /var/lib/odoo
db_host = odoo-db
db_maxconn = 64
db_name = mymambo19
list_db = False
;db_password = GR77blc01
db_password = odoo
db_port = 5432
db_sslmode = prefer
db_template = template1
db_user = odoo
;db_user = odoo19
;dbfilter = .*
;dbfilter = ^mycompany.*$
dbfilter = ^mymambo19$
email_from = False;
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 48192
limit_time_cpu = 10660
http_interface = 0.0.0.0
proxy_mode = True
workers = 2                 
max_cron_threads = 1
http_port = 8069
gevent_port = 8072
server_wide_modules = base, web, bus	

