services:
  wud:
    image: getwud/wud:latest
    container_name: wud
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./store:/store

    networks:
      - traefik_default

    environment:
      - WUD_WATCHER_LOCAL_CRON=0 8 * * *
      - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=true

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.wud.rule=Host(`wud.nolte-eng.de`)"
      - "traefik.http.routers.wud.entrypoints=websecure"
      - "traefik.http.routers.wud.tls=true"
      - "traefik.http.routers.wud.tls.certresolver=cloudflare"
      - "traefik.http.services.wud.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.wud-auth.basicauth.users=admin:$$2y$$05$$ypQp4IXelJk17zVoTIO5pu7o7S0LIgaqlHA45mEYdQ0KRa9.mWP.O"
      - "traefik.http.routers.wud.middlewares=wud-auth"
networks:
  traefik_default:
    external: true
